import type { NetworkProfile } from "./types";

export const MOCK_PROFILES: NetworkProfile[] = [
  {
    id: "1",
    firstName: "Ethan",
    lastName: "Hansen",
    contactType: "alumni",
    currentCompany: "ICBC",
    currentRole: "UX Engineer",
    currentRoleDesc: "Designing internal financial tools",
    pastExperience: [
      {
        company: "Google",
        role: "Marketing Analyst",
        desc: "Worked on Gemini GTM strategy",
      },
    ],
    bio: "BUCS alum interested in design systems and startups.",
    hobbies: ["Design", "Coffee", "Startups"],
    linkedinUrl: "https://www.linkedin.com/in/ethanth",
    email: "ethan.t.hansen@gmail.com",
    openToContact: true,
    profilePhotoUrl: "https://avatar.vercel.sh/ethan",
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    firstName: "Sarah",
    lastName: "Chen",
    contactType: "alumni",
    currentCompany: "Shopify",
    currentRole: "Product Manager",
    currentRoleDesc: "Leading merchant experience initiatives",
    pastExperience: [
      {
        company: "Microsoft",
        role: "PM Intern",
        desc: "Worked on Azure portal improvements",
      },
    ],
    bio: "Commerce alum passionate about e-commerce and product strategy.",
    hobbies: ["Hiking", "Photography", "Reading"],
    linkedinUrl: "https://www.linkedin.com/in/sarahchen",
    email: "sarah.chen@example.com",
    openToContact: true,
    profilePhotoUrl: "https://avatar.vercel.sh/sarah",
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    firstName: "James",
    lastName: "Park",
    contactType: "exec",
    currentCompany: "Lululemon",
    currentRole: "VP of Engineering",
    currentRoleDesc: "Overseeing digital transformation",
    pastExperience: [
      {
        company: "Amazon",
        role: "Senior SDE",
        desc: "Built distributed systems for AWS",
      },
      {
        company: "Salesforce",
        role: "Tech Lead",
        desc: "Led platform architecture",
      },
    ],
    bio: "CS alum now leading engineering teams in retail tech.",
    hobbies: ["Running", "Mentorship", "Tech talks"],
    linkedinUrl: "https://www.linkedin.com/in/jamespark",
    email: "james.park@example.com",
    openToContact: true,
    profilePhotoUrl: "https://avatar.vercel.sh/james",
    createdAt: new Date().toISOString(),
  },
    {
    id: "4",
    firstName: "Ethan",
    lastName: "Hansen",
    contactType: "alumni",
    currentCompany: "ICBC",
    currentRole: "UX Engineer",
    currentRoleDesc: "Designing internal financial tools",
    pastExperience: [
      {
        company: "Google",
        role: "Marketing Analyst",
        desc: "Worked on Gemini GTM strategy",
      },
    ],
    bio: "BUCS alum interested in design systems and startups.",
    hobbies: ["Design", "Coffee", "Startups"],
    linkedinUrl: "https://www.linkedin.com/in/ethanth",
    email: "ethan.t.hansen@gmail.com",
    openToContact: true,
    profilePhotoUrl: "https://avatar.vercel.sh/ethan",
    createdAt: new Date().toISOString(),
  },
];